export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
};
export const formationConstants = {
  GET_FORMATION_REQUEST: 'GET_FORMATION_REQUEST',
  GET_FORMATION_FAILURE: 'GET_FORMATION_FAILURE',
  GET_FORMATION_SUCCESS: 'GET_FORMATION_SUCCESS',
};
export const registerConstants = {
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
};
export const centre_formationConstants = {
  GET_CENTRE_FORMATION_REQUEST: 'GET_CENTRE_FORMATION_REQUEST',
  GET_CENTRE_FORMATION_FAILURE: 'GET_CENTRE_FORMATION_FAILURE',
  GET_CENTRE_FORMATION_SUCCESS: 'GET_CENTRE_FORMATION_SUCCESS',
};


export const formateurConstants = {
  GET_FORMATEUR_REQUEST: 'GET_FORMATEUR_REQUEST',
  GET_FORMATEUR_FAILURE: 'GET_FORMATEUR_FAILURE',
  GET_FORMATEUR_SUCCESS: 'GET_FORMATEUR_SUCCESS',
};